// <auto-generated />
using System;
using Houk_IT310_CMS_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Houk_IT310_CMS_Backend.Migrations
{
    [DbContext(typeof(CMS_BackendContext))]
    partial class CMS_BackendContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Houk_IT310_CMS_Backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Food"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Tech"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "News"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Tacos"
                        });
                });

            modelBuilder.Entity("Houk_IT310_CMS_Backend.Models.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("ContentId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Content");

                    b.HasData(
                        new
                        {
                            ContentId = 1,
                            Author = "Lee",
                            Body = "It's toasty",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 1, 30, 20, 28, 28, 434, DateTimeKind.Local).AddTicks(9126),
                            Title = "Toast Post",
                            UpdatedAt = new DateTime(2025, 1, 30, 20, 28, 28, 434, DateTimeKind.Local).AddTicks(9183),
                            Visibility = 0
                        },
                        new
                        {
                            ContentId = 2,
                            Author = "Lee",
                            Body = "And sometimes useful",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 30, 20, 28, 28, 434, DateTimeKind.Local).AddTicks(9186),
                            Title = "AI is cool",
                            UpdatedAt = new DateTime(2025, 1, 30, 20, 28, 28, 434, DateTimeKind.Local).AddTicks(9187),
                            Visibility = 0
                        },
                        new
                        {
                            ContentId = 3,
                            Author = "Lee",
                            Body = "This is my first post.",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 30, 20, 28, 28, 434, DateTimeKind.Local).AddTicks(9190),
                            Title = "Guess What?",
                            UpdatedAt = new DateTime(2025, 1, 30, 20, 28, 28, 434, DateTimeKind.Local).AddTicks(9191),
                            Visibility = 0
                        },
                        new
                        {
                            ContentId = 4,
                            Author = "Lee",
                            Body = "Let's eat tacos",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 30, 20, 28, 28, 434, DateTimeKind.Local).AddTicks(9193),
                            Title = "Taco Time",
                            UpdatedAt = new DateTime(2025, 1, 30, 20, 28, 28, 434, DateTimeKind.Local).AddTicks(9194),
                            Visibility = 0
                        });
                });

            modelBuilder.Entity("Houk_IT310_CMS_Backend.Models.Content", b =>
                {
                    b.HasOne("Houk_IT310_CMS_Backend.Models.Category", "Category")
                        .WithMany("PostedContent")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Houk_IT310_CMS_Backend.Models.Category", b =>
                {
                    b.Navigation("PostedContent");
                });
#pragma warning restore 612, 618
        }
    }
}
